### Week 9: Day 3 - Introduction To Linear Algebra

#### Introduction to linear Algebra

##### Mathematics with Iliya Valchanov

Linear algebra is the branch of mathematics concerning linear equations

such as: In three-dimensional Euclidean 

space, these three planes represent ...

Identity element of scalar 

multiplication: 1v = v, ...

Identity element of addition: There 

exists an el...

Inverse elements of addition: For every

v in V, t...

Commutativity of addition: u + v = v + 

u
‎Linear equation · ‎Multilinear algebra 

· ‎Numerical linear · ‎Outline

Linear algebra is a branch of mathematics that deals with linear 

equations and their representations in the vector space using matrices.

Our linear algebra journey starts with matrix.

A matrix is a collection of numbers ordered in  rows and columns 

Each of these values is an element of the matrix.

Our matrix have a total of 6 elements.

We are dealing with  a matrix and we put all the elements in bracket.

We normally dente a matrix with a capital letter

Our matrix A has 2 rows (horizontal)

columns (vertical),

In linear Algebra , rows and columns 

are the two dimension of the matrix

.A has 2 rows and 3 columns 

A 

2x3 

Hence, we say its dimensions are 2 by3 

or better A is a 2-by-3 matrix.

Normally, we take note on that and put 

it below the letter A

Matrices seem similar to tables and spreadsheets at first.

However,the purpose of matrices is not simply to store values .

Matrices are main characters in the mathematical operations.

Two matrices can be added

. Addition

. Subtracted

. Multiplication

. Divided

Hence,linear Algebra is similar to algebra in the type of operation they 

are but differs in how and when these 

operations are implemented and if they are permited at all.

A matrix can only contain Numbers, symbols, or expressions.

The idea is that the later two are nothing more than a generalized representation of numbers .

For instance , the collection of these two symbols

This shows a diferent 2 by 3 matrics.
a b

C have 4 elements and s a 2x2  matrics but is contents are not values but expression.

What about the size of a matrix ?

Matrix can be of any size and in a genaral cas we are talking about mxn matrix.

Sometimes we need to refernce a 

particular element of A

The element A are denoted with a lower 

case a and two numbers indicating the 

respective element position in terms of row and column

For instance aij is the element and position ij

Where i is the respective row and j is the respective column

Hence, if we want to fill in the 

matrics, it will start from 

a11 a12 a13 .... a1n to finish the 

first row.

similarly we got,
a11

a21

a31

.
.
.
am1

 To complete the first column

the last element of the matrix is amn

And the total number of elements is mxn

In conclusion,in most programming language ,how be it not in all of them,

Arrays starts from 0 rather than 1.

In python for instance, arrays starts from 0.

Hence ,keep that in mind when coding.

#### Scalars and Vectors

A scalar is a matrix with one row and one column.

    
   [a11]} 1 row
   1 column

All numbers we know from algebra are referred to as scalers in linear algebra.

the numbers below are scalers

In [ ]:
[15]; [1]; [2]; [-5]; ...[n] etc

Since scalars are objects with no dimensions.

They have important properties.

Vectors

They are also very common objects in linear algebra.

They sit somewhere between scalars and matrices as they have one dimension

Example od vector with 3 elements

{5]
[-2]}  3 rows
[4]
3x1 matrix
vector

Notice that this vector is nothing more than 3 x 1 matrix.

Its single dimension is the number of rows it has.

Since a scalar is basically a number ,

A vector is practically the simplest linear algebraic object.

Due to the many application of vectors , they have a special name and are 

often examined as a seperate object 

Moreover, it is more more common to view a matrix as a collection of 

vectors rather than a vector as a  special case of a matrix

Generally ,there are two types of vectors:

Row vectors

Column vectors

We just explored a row vector but we can have a column vector as follows

[3 4 5 8]
 column vector

In most cases, we are interested in a number of element a vector contains.

We refer to that number as the lengh of the vector.

The first vector we saw have a length of 3 and the second one have a length of 4 .

In the general case, a vectors length can be designated as m 

A column vector will have dimension m by 1.

and the row vector 1 by m

Regarding the notation, the element of a vector x will be x1,x2,...xn

SUMMARY

We have matrixes that have 2 dimensions

mxn

Vectors that have a single dimension, mx1

And scalars that have no dimension and are 1x1.

#### Linear algebra and Geometry 

Mathematics works based on Analogies 

with linear algebra that's extremely relevant.

We said  a scatar has no dimension.

Moreso, the geometry idea of a point do

not have a dimension.

A point is the simplest object in terms of geology.

It has no direction and no asides.

A scaler is like a point.


We have vectors and a vector has one dimension.

It is like a line but how ever it has a direction.

It can be oriented in many ways

WE can plot this in two dimensions but 

to get into 2D we need something else.

The only way to get from a line to a 

plane is by crossing it with another line.

Two dimensional space is defined by 2 lines.

Why two lines means two vectors

In linear algebra, a matrix is a collection of vectors or any two 

dimentional plain can be represented by a matrix.

This idea though simple is extremely powerful.

Lets explore the two dimensional plane

IF i want to represent a vector, for eg

2,5 , it will be a line from the origin 

of the plane to the point position 2,5 

The direction is always from the orign 

of the graph to the end point.

The vector -2, -5 will be exactly the opposite of the first one.

the vector -2,3 will appear same way and so on.

Each of this vector has a direction 

determined by its values.

This vector is 1,0 and the other one is 0,1.

Taking this two vectors together we can create a matrix.

This matrix is basically made up of 

small portions of two axis. x, y

What is important though is that if i remove everything else from the graph ,

this matrix will define the two dimensional planes we were just looking at.

Every two vector we take will define 

the two 2d plane we are looking at.

A nice free online tool to play with is the 3D vector plotter by Academo.org

You can spefify each vector of interest and fidle with the plot.

This website allows you to create all kinds of matrics of the 3x3 and with 

this you can understand better the  geometry concept of  vectors and metrics.

#### Scalars, Vectors and Matrics as Python Arrays

Data scientist uses linear Algebra

How to code a matrix ,vector and scaler

The simplest and most flexible way to work with scalars,vectors and matrices is by using arrays. 

Moreover, we will use the numpy functionality aa the optimize for such operation.

Import the relevant libraries

In [1]:
import numpy as np

#### Declaring scalars, vectors and matrices

##### Scalars

Lets start by declaring a scalar.

In python and many other languages , an integer or float are doing the job.

hence, s=5 will do

In [3]:
s=5

In [4]:
s

5

##### Vectors

How would we declare a vector?

say we are looking at the same vector as before.

Lets declare a new variable v = np. array([5,-2,4])

Note, that there is round bracket for the np.array method and square bracket[] for the vector itself.

Printing v, we will see that it contains 3 values we wanted.

In [5]:
v = np.array([5, -2, 4])

In [6]:
v

array([ 5, -2,  4])

In [ ]:
We have created a vector ,

By default, v is a row vector

##### Matrices

Lets create a matrix

m = np.array() round brackets

This matrix actually contains 2 vectors as seen below

In [7]:
m = np.array([[5,12,6],[-3,0,14]])

In [8]:
m

array([[ 5, 12,  6],
       [-3,  0, 14]])

As you can see we have a matrix.

However, there are several programming and interations we need to make.

We will focus on them now as they are paramount for coding.

##### Data types

If we write type() returns the data type of a given variable

In [9]:
type(s)

int

it means that s is an integer, then v and m are nd arrays.

Nd arraya stands for n dimentional arrayas.

Most especially the vector v is a 1- dimensional array and matrix m is a 2-dimensional array.

In general, we can have n-dimensional arrays.

In [10]:
type(v)

numpy.ndarray

In [11]:
type(m)

numpy.ndarray

Finally, if i want s to be consistent with the others i can also declare it  as an array as well.

In [14]:
s_array = np.array(5)

s_array

array(5)

In [15]:
type (s_array)

numpy.ndarray

Hence, we can see it as an ndarray.

and this is another way you can create a scalar in python.

For pracical purposes,in python and within numpy,integers, floats and arrays with one element behaves in thesame way regarding linear algebraic operations.

##### Data shapes

There is a method called shape which we can apply to an object to check the dimensionality or shape

Shape returns the shape (dimensions) of a variable.

In [16]:
m.shape

(2, 3)

This returns 2x3. this is also the expected result. as you are dealing with a two by 3 matrix.

In [17]:
v.shape

(3,)

This returns 3 comma

this is something you will see in some programming languages and not all.

It is basically indicating that in the memory of the computer the object has 3 elements whicha are stored in order.

In [ ]:
We can check the shape of s

#s.shape

We will get an error because int objects dont have shape.

If we try same method on s_array.shape we simply have parenthesis.

This is because a scalar is a zero dimensional object because it has no shape

In [22]:
s_array.shape

()

##### Creating  a column vector

Depending on our needs we can use the reshape method to create a row or  a column vector.

reshape gives an array a new shape ,without changing its data.

There aree two possibilities , a row vector or a column vector

In [18]:
v.reshape(1,3)

array([[ 5, -2,  4]])

In [19]:
v.reshape(3,1)

array([[ 5],
       [-2],
       [ 4]])

#### What is a Tensor

In mathematics, a tensor is an algebraic object that describes a 

multilinear relationship between sets of algebraic objects related to a vector space.

Tensorflow is one the state of the act  deep learning framework developed by google. 

It works in a peculiar way but one of its main characteristics is that it works with Tensors.

##### What is  a Tensor

The mathematical concept of a tensor could be broadly explained in this way.

A scalar has the lowest dimensionality and is always one by one

In [ ]:
[15]

In [ ]:
It can be thought of  
. A vector of length 1 

. or

.A  1x1 matrix

It is followed by a vector,where each element of that vector is a scalar.

The dimensions of a scalar are nothing but 

. m x 1 or 1 x m matrix



Then we have matrices which are nothing 

more than a collection of vectors

In [ ]:
The direction of a matrix are m x n

In [ ]:
[x1]
[x2]
.
.
.
[xm]

Matrix is a collection of m vectors of dimensions m x 1.

or n vectors of dimension n x 1

Furthermore, since scalars make up vectors .
you can also think of a matric as a collection of scalars as well.

A tensor is the most general concept.

Scalars, vectors and matrices are all tensors of Rank 0 1 2 respectively.

Tensors are simply the generalization of the concepts we have seen so far.

The one we are yet to see is  atensor of RANK 3.


Its dimensions are k x m x n

It can be thought of  as a collection of matrices.

In terms of programming, a tensor is no different than an  ndarray.


Tensors can be stored in ndarrays and that is how we often deal with the issue.

##### Create a tensor out of two matrices

Our first matrix m1 will be from the first example.

The matrix m2 will be a different one 

with the element, [9,8 7], [1,3,-5]

In [23]:
m1 = np.array([[5,12,6],[-3,0,14]])
m1

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [24]:
m2 = np.array([[9,8,7],[1,3,-5]])
m2

array([[ 9,  8,  7],
       [ 1,  3, -5]])

Now lets create an array t with two elements m1 and m2, after printing t we realise that it contains both matrices

In [25]:
t = np.array([m1,m2])

In [26]:
t

array([[[ 5, 12,  6],
        [-3,  0, 14]],

       [[ 9,  8,  7],
        [ 1,  3, -5]]])

#### checking its shape

In [27]:
t.shape

(2, 2, 3)

it is a 2 x 2 x 3 object.

It contains 2 matrices of 2 x 3 each

##### Manually create a tensor

If we want to manually create  atensor, we will need to write this line of code.

As you can imagine tensors with lots of 

elements are very hard to manually create.

Not only because there are many 

elements but also because of those confusing brackets.

Usually we will load, transform and pre-proess the data to get tensors.

However, it is always good to have thr theoritical background.

In [28]:
t_manual = np.array([[[5,12, 0], [-3, 0, 14]], [[9, 8, 7], [1,3, -5]]])

In [29]:
t_manual

array([[[ 5, 12,  0],
        [-3,  0, 14]],

       [[ 9,  8,  7],
        [ 1,  3, -5]]])

#### Adding and Subtraction

We can add and subtract matrices

In [ ]:
ADDITION

Addition is very easy

one important condition is tha the two 

matrices must have thesame dimension

Say we have the two matrices M1 and M2

They are both 2x3 matrices.

If we want to add the two, all we need 

to do is to add the corresponding enteries one to the other.

In [ ]:
M1 = [ 5 12 6]       M2 = [9 8 7]
2x3  [-3  0 14]      2x3  [1 3 -5]

The result is a new 2x3 method

For the element at position 1 x 1 we have 5 + 9

For the element at position 1x2 ,we have 12 + 8

For the element at position ,1x3 we have 6 + 7

We continue adding them until position , 2x3 where we have got  14 +-5


All we have to do is to make the simple

calculation and reach the solution

If we want to add the matrices in 

python, we need to declare them and then use the + sign

Import the relevant libraries

In [1]:
import numpy as np

##### Addition

In [2]:
m1 = np.array([[5,12,6],[-3,0,14]])
m1

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [5]:
m2 = np.array([[9,8,7],[1,3,-5]])
m2

array([[ 9,  8,  7],
       [ 1,  3, -5]])

In [6]:
m1 + m2

array([[14, 20, 13],
       [-2,  3,  9]])

Subtraction is a type of addition so 

same rule applies there.

lets have this two matrices.  

M3 and M4

In other to find the difference between the two matrices.

We just need to calculate the

diffference between each two corresponding elements.

Note, that the two matrices have the same dimension.

This time 2x2.

The final result is -2 8 on the first row and -5 -4 on the second row

In [ ]:
[-2 8]  
[-5 -4]

In terms of coding, things are not 

different, we declare the 2 matrices and find their diffence

##### Difference

##### Example 1

In [7]:
m3 = np.array([[5,3],[-2,4]])
m4 = np.array([[7,-5],[3,8]])

In [8]:
m3

array([[ 5,  3],
       [-2,  4]])

In [9]:
m4

array([[ 7, -5],
       [ 3,  8]])

SUBTRACTION WITH FLOAT

EXAMPLE

The 2 matrices are both 3 x 2 so they are compatible.

In [10]:
m5 = np.array([[22.33, -4.73], [-203.14,1200.02]])
m5

array([[  22.33,   -4.73],
       [-203.14, 1200.02]])

In [15]:
m6 = np.array([[131.13,448.29],[-340.21,1.06],[30.41,424.99]])
m6

array([[ 131.13,  448.29],
       [-340.21,    1.06],
       [  30.41,  424.99]])

In [18]:
m5 - m6

ValueError: operands could not be broadcast together with shapes (2,2) (3,2) 

##### Adding vectors together

What about  Vectors ?



Since vectors are nothing more than 1 

dimensional matrices, same rules apply.

Lets take the vector 1,2,3,4,5 and 

vector 5, 4 3, 2, 1 and add them together.

In [21]:
v1 = np.array([1,2,3,4,5])
v2 = np.array([5,4,3,2,1])

In [22]:
v1 + v2

array([6, 6, 6, 6, 6])

With vectors we only care about the length.

the two vectors have thesame length, so they are compatible.

There is only one way to add them up.

first element with first element, second element with second and so  on.

The result is a vector of length 5 where all nteries a 6 

What about the difference ?

It is a vector of length 5 with 

elements of -4,-2, 0, 2, 4

In [23]:
v1-v2

array([-4, -2,  0,  2,  4])

#### Errors when Adding Matrices

Lets talk a bit more about scalars .

Scalars are more peculiar than high

dimension objects because they are single numbers.

we didnt talk about it , but i believe 

we know how to add two scalars together.

##### Import the necessary libraries

In [24]:
import numpy as np

##### Addition

###### Addition of scalars

In [25]:
5 + 5

10

In [27]:
10 - 4

6

We also know that in other to add 

vectors and matrices together their forms must match.

We are not allowed to add vectors of 

different lenghts and matrices with different dimension.

Such operations are not allowed in 

linear algebra and python knows that.

For instance, if i try to add 2x3 

matrics , we will get error message

"operands could not be brought together 

with shape" (2,3) (2,2)

Showing you the shape in question.

Similarly, if we try to add two vectors

with different lengths we will receive thesame error

Mathematically, these operations dont 

make sense, so it cant be executed.

##### Exceptions (addition with a scalar)

However, there is one exception.

Because of how arrays work in python 

and many other languages we can 

actually add scalars to matrices and vectors.

For instance, if i add 1 to the matrix 

m1, you can see that one was adeded 

element wise.

In other words , each element was increased by 1

In [28]:
m1

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [29]:
m1 + 1

array([[ 6, 13,  7],
       [-2,  1, 15]])

Similarly, if i add 1 to the vector 

v1,it will be added element -wise

In [30]:
v1

array([1, 2, 3, 4, 5])

In [31]:
v1 + 1

array([2, 3, 4, 5, 6])

Mathematically, this operation is not

allowed as their shape are different.

But in programming , specifically , in python it works.

It is important to be aware of this peculiarity.

The result has a meaaning in terms of arrays but not in terms of linear algebra

And this is one of the big differences 

between the conceots of nd arrays and tensors

In [32]:
m1 + np.array([1])

array([[ 6, 13,  7],
       [-2,  1, 15]])

In [33]:
v1 + np.array([1])

array([2, 3, 4, 5, 6])

#### Transpose of a Matrix

Lets start from vectors.

We already know that vectors are either rows or columns.

Hence lets execute the column vector

[1,2,3]

There is a special operation when it comes to row vector.

We can transpose it .

Transposing the column vector  123 will

yield in a row vector 123

In [ ]:
Another example:
    
The row vector [1 2 3] T 
                xT
= colunm vector [1] 
                [2]
                [3]
                
                (xT) = x

If we transpose x twicw , we get x ie 

(xT)^T = x

Another Example:

However, there are very important considerations.

. 1 when we transpose a vector, we are not loosing any information

The values are not changing or transforming, only thier positions is.

2. Transposing the same vector twice yields the initial vector(object)

.3 Our initial vector 1,2,3 has a length of 3, in other words it was a 

3x1 matrix and by transposing it , it remained the vector of lenght 3 but became a 1x3 matrix.

A 3x1 matrix transposed is a 3x1 matrix

Transposing turns all the rows into column and vice versa.

In terms of dimension, when transposed, mxn T matrix becomes nxm matrix.

EXAMPlE

In [ ]:
A transposed gives

A is  a 2x3 matrix when transposed it becomes a 3x2 matrix.

We can see that the first colunm of A became the first row A transposed.

The second column of A became the second row A transposed.

And the 3rd column became the 3rd row.

This is how we transpose a matrix.

THe initial matrix A is nothing more than a collection of two row vectors.

Transposing the matrix A is means transposing 

each of those vectors and putting them back together.

So transposing matrices is nothing more

than transposing a bunch of vectors.

##### Import the relevant libraries

In [34]:
import numpy as np

##### Transposing matrices

First we declare A as an np.array.

array.T returns the transpose of an 

array(matrix)

In order to get the transpose of A we 

simply write A.T ie A dot capital T. 

In [35]:
A = np.array([[5,12,6],[-3,0,14]])
A

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [36]:
A.T

array([[ 5, -3],
       [12,  0],
       [ 6, 14]])

In [ ]:
EXAMPLE 2:

Taking the 2x2 matrix containing 5,3 

and -2, 4and transposing it , we get 

another 2x2 matrix.

In [37]:
B = np.array([[5,3], [-2,4]])
B

array([[ 5,  3],
       [-2,  4]])

In [38]:
B.T

array([[ 5, -2],
       [ 3,  4]])

In [ ]:
EXAMPLE 3

We will be using a 4x3 matrix.

When it is transposed the result below is what we will get.

Observe that this operation is nothing more than transposing several vectors 1x1

In [39]:
C = np.array([[4,-5],[8,12],[-2,-3],[19,0]])
C

array([[ 4, -5],
       [ 8, 12],
       [-2, -3],
       [19,  0]])

In [40]:
C.T

array([[ 4,  8, -2, 19],
       [-5, 12, -3,  0]])

##### Transposing scalars

Here are some further clarifications.

Any scalar when transposed equals itself.

They are not the most interesting concept


In [45]:
s = np.array([5])


In [46]:
s.T

array([5])

##### Transposing vectors

We have the vector x = 1, 2 3, 

transposing it will yield same result, 

this is because in python 1 dimensional 

arrays do not really get transposed( in the memory of the computer)

In [47]:
x = np.array([1,2,3])
x

array([1, 2, 3])

In [48]:
x.T

array([1, 2, 3])

Remember its shape  is 3,

In [49]:
x.shape

(3,)

If we resahpe it into a 3x1 matrix or 2 

dimensional array, we will be able to transpose it.

This is another peculiarity you must 

consider when working with nd.arrays in python

In [50]:
x_reshaped = x.reshape(1,3)
x_reshaped

array([[1, 2, 3]])

In [52]:
x_reshaped.T

array([[1],
       [2],
       [3]])

#### Dot Product

#### Multiplication

Scalar Multiplication

Dot represents multiplication

5 times 6 is 30

In [ ]:
[6] .[5] = [30]

[10] . [-2] = [-20]

VECTOR MULTIPLICATION

It is much more interesting to investigate vector multiplication.

In [ ]:
[2]   X   [1]
[8]       [-7]
[-4]      [3]

If we want to multiply them, the condition is that they must be 

compatible or in order words they must have thesame length.

Condition : They must be of thesame length

Ther are two types of products we can get

.1 Dot or inner product

.2 Tensor or outer product

Here we will not be needing the outer products.

An outer product is a procedure in linear algebra that combines two vectors (Banchoff & Wermer, 1992).

Let a be a column vector with x entries, and let b' be a row vector with y entries. The outer product of 

these two vectors is D = ab' where D will be a matrix that will have x rows and y columns.

Dot product is heavily used but we 

will talk about multiplying vectors and matrices and what they mean.

Other popular names for the Dot product are inner or scalar.

The Notation is  a . signifying that it is a dot product

How it works?

We multiply each 2 corresponding 

element and find a sum.

In our case, 2x1 + x-7 + -4 x3 = -66

As you can see we multiplied 2 vectors and got a scalar product.

Furthermore  note that the dot product

is nothing more than the 'sum of the 

products of the corressponding elements'.

In python, we wil need to declare the two vectors.

We will use the method dot provided by numpy

##### Import relevant libraries

In [3]:
import numpy as np

###### Dot product

In [2]:
x = np.array([2,8,-4])
y = np.array([1,-7,3])

In [3]:
np.dot(x,y)

-66

This gives us the dot product which is -66.

In [ ]:
EXAMPLE 2:

In [5]:
u = np.array([0, 2, 5, 8])
v = np.array([20,3,4,-1])

In [6]:
np.dot(u,v)

18

##### Scalar * Scalar

What about the operation at the beginning of the lecture.


In [8]:
np.dot(5,6)

30

This was a scalar product of two scalar that resulted in another scalar

In [9]:
np.dot(10,-2)

-20

##### Scalar * Vector

What about we multiply  a scalar by  a vector ?

When we multiply a vector by a scalar, we get avector with thesame length.

Its inconvent are multiplied by the scalar.

For our case ,we will get 2x5 , 8x5, and -4x5 

the result is  10, 40, -20

In [10]:
x

array([ 2,  8, -4])

In [11]:
5*x

array([ 10,  40, -20])

What is interesting is that the 

initial vector has been scaled 5times(thus the name).

So multiplication of a scalar does not change the shape but only the scale of the values.

#### Dot Product of Matrices

#### Matrix multiplication

##### Scalar *Matrix

In [12]:
A = np.array([[5,12,6],[-3,9,14]])
A

array([[ 5, 12,  6],
       [-3,  9, 14]])

In [13]:
3*A

array([[15, 36, 18],
       [-9, 27, 42]])

Similar to what we say in the last 

lesson, the shape of the matrix doesnt change,it just got scaled.

We keep the shape and multiply each element by 3.

The result is as seen above.

How do we multiply a matrix with another matrix.

Using thesame concept the Dot product we can multiply two matrices.

There is a compatibility measure here as well.

Condition: we can only multiply an mxn
written with the matrix and dimension n x k.

Basically, the second dimension of the

first matrix have to match the first dimension of the second matrix.

Hence, we can multiply a 2x3 matix with a 3x1 matrix.

Actually we can multiply it by 3x2, 3x3, 3x4 and until 3xk matrix.

What is important is that those tress are matching.

Similarly, if i want to multiply a

5 x 7 matrix

Compatible matrices for 

multiplications are 7 x 1, 7 x 2,

7 x 7 and so on.

What about the dimension of the product ?

Compatibility measures: 

they need to have matching forms.

When multiplying an m x n matrix with 

an n x k matrix, the output is an

m x k matrix.

For instance, a 2 x 3 matrix times a

3 x 6 matrix will give us a 2 x 6 matrix.

A 3 x 4 matrix times a 4 x 2 matrix 

will give us a 3 x 2 matrix.

A 100 x 300 matrix times 300 x 3 

matrix will give us a 100 x 3 matrix

Basically, which ever dimension is 

repeating will disapper in the 

resulting matrix.

How do we multiply matrices ?

Example using two matrices:
    

These are 2 vectors or 3 x 1 matrices.

In other to multiply them, they need to have matching forms.



To find their dot product, we 

Transpose the first one and get a 

1 x 3 and a 3 x 1

This is done because whe we have a dot

product , we always multiply a row vector times a column vector.

Always remember that!

The result of this multiplication is a

1 x 1 form or scalar.

We reach this calar by multiplying the

corresponding elementand summuing everything up.

We already know that the concept is thesame.

Then we take the two matrices and multiply them.

The first is thesame one from the 

beginning of the example.

The second will be a 3 x 2 matrix

The first thing we need to do is to 

check the compatibility.

We have 2 x3 and 3 x2 .

The forms match so we are good to go

Next step is to find the shape of the output matrix.

The matching dimension( 3 , 3) disappears, 

hence the resulting shape is 2 x 2. 

Finally, we need to do the multiplication.

Two important things to note:

.1 Matrices are nothing more tan a collection of vectors.

.2 When we have a dot product ,we always multiply a row vector times a column vector.

In other to find the dot product of the 2 matrices,

We need to find the dot product of the vectors they are made of

Which is 5 x 2 + 12 x 8 + 6 x 3 = 124

Hence , 124 is also the first element of the output matrix.

In [ ]:
Next we find the dot produc of 
[5, 12 6]  with the second vector

[-1]
[0]          = -5
[0]

In [ ]:
which is (5 x -1) +( 12 x 0) + (6 x 0)
 = -5

The result is -5 which is the second element of the output matrix .

Now lets look at the second row of the initial matrix.

In [ ]:
(-3 x 2) + (0 X 8) + (14 x 3) = 36

This is the first value on the second row of the output matrix.

Notice that the row vector from the first matrix determines the row and the output matrix.

Thesame way the column vectors from the second matrix determine the column of the respective value.

Finally ,let's find the last dot product.



(-3 x -1) + (0 x 0) + (14 x 0)  = 3

This is the second value on the second row of the output.

In [ ]:
the product matrix is now

[124  -5]
[36   3]

2 x2 matrices

In teerms of code,it is very simple, we use the method np.dot and the two 

matrices and immediately get the result

##### Matrix * Matrix

##### Example 1

In [14]:
B = np.array([[2,-1],[8,0],[3,0]])
B

array([[ 2, -1],
       [ 8,  0],
       [ 3,  0]])

In [15]:
np.dot(A,B)

array([[124,  -5],
       [108,   3]])

##### Example 2

We will use two big matrices.

The first matrix is 4 x 5 and the second matrix is 5 x 2.

First thing , are the matrices compatible?

Yes they are.

We have ( 5 , 5)

Second is to find the shape of the output matrix , which is 4 x 2

Next we divide the fisrt matrix into row vectors and the second matrix into column vectors.

We have a total of 4 rows vector and 2 column vector.

We need to find the dot product of the first row vector and the first column vector. the result is - 71

(-12 x 6) + (5 x 8) + (-5 x 2) +

(1 X 7) +( 6 x -6)  = 71

Next we multiply the first row vctor 

with the second column vector,
We get -48

We continue in the known way until we fill the product matrix. 

In [5]:
C = np.array([[-12, 5, -5, 1, 6],[6, -2, 0, 0, -3],[10, 2, 0, 8, 0],[0, -4, 8, 3, -6]])
C

array([[-12,   5,  -5,   1,   6],
       [  6,  -2,   0,   0,  -3],
       [ 10,   2,   0,   8,   0],
       [  0,  -4,   8,   3,  -6]])

In [7]:
D = np.array([[6, -1],[8,-4],[2, -2],[7,4],[-6,-9]])
D

array([[ 6, -1],
       [ 8, -4],
       [ 2, -2],
       [ 7,  4],
       [-6, -9]])

In [8]:
np.dot(C,D)

array([[-71, -48],
       [ 38,  29],
       [132,  14],
       [ 41,  66]])

##### Example 3

A 3 x 4 matrix and  a 2 x 3 matrix

What will the dimension of the output be ?


You may think is 3 x 3

But it is not

Hence , the dimension is nothing

The two matrices are not compatible.


It is important to note that more 

often than not ,you may not be able to multiply 2 matrices.

So is important to take good note of the shapes.

Linear Algebra doesnt seen that hard after all.

##### Question

5. Let A and B be 3×3 (square) 

matrices. Which of the following must 

necessarily hold true? Check all that apply.

##### Answer

If A is the 3 x 3 identity matrix, 

then A x B X A = B X A

#### Why is linear Algebra Useful

There are very many operations in linear Algebra.

Applications in data science and there 

are sevaral ones of high importance 

which we will explore and use later on.

Some are easy to grasp but others not yet.

We will explore three namely:
    
 . Vectorized code also known as array programming

. Image recognition

. Dimensionality reduction
       

The simplest and most commonly used one is Vectorized code.

We can certainly clain that the price of a house depends on its size.

Suppose you know that the exact 

relationship for some neigbourhood is given by the equation.

Price = 10,190 + 223 ^ size = $

Moreover,you know the sizes of 5 houses

10,190 + 223 *693 = 164729

10,190 + 223 *656 = 156478

10,190 + 223 *1060 = 246570

10,190 + 223 *487 = 118791

10,190 + 223  *1276 = 294515

What you want to do is to plug in size

in the  equation and find the price of each house

Doing this manually will be quite tedious.
one way to deal with this problem will be to create a loop and and itirate  over the sizes and multiply each one of then by 223 * size[i] and adding 10,190 

For i in range(100):
print (10190 + 223 * size [i])

but we are smarter than that since we know some linear Algebra already.

A 5  by 2 matrix and a vector of line 2.

The matrix contains a column of 1 and the other with the sizes of the houses.

The vector contains 10190 and 223

The numbers from the equation

If we go about multiplying them, we will et a vector of length 5 and the first element will be as explained above

By inspecting this expressing we quickly  realize that the resulting vector contains all the manual calculation we made earlier to find the prices

Inmachine learning and linear regressions in particular,this is exactly how algorithmns work

We have inputs matrice, weight and output matrix.

Note, if you have 10,000 inputs, input matrix will be 10000 x 2

Weight matrix will be 2 x 1 

When we multiply them, the resulting outputs matrix will be 10,000 by 1

This shows us that no matter the number of outputs , we will get as many as output

Moreover, the equation does not change as it only contains the two coefficients.

10190
223

This concept will turn quite helpful in macine learning study.

Whenever we are using linear algebra to compute many values simultaneously, 

we call this array programming or vectorizing code.

It is important to stress that array programming is much much faster.

We have libraries like numpy which are optimized to perform this kind of operations which greatly increases the computation proficiency of our code.

#### Image recognition

In the last few years 

. Deep learning 
.Deep neural networks 

in particular, calculate image recognition


On the fore front are  convolutional neural networks(CNNS).

What is the basic idea, you can take a photo ,feed it to the algorithmn and classify it.

Famous examples are the MNST dataset where the task is to classify hand written digits,

CIFAR 10 where the task is to classify animals and vehicles.

CIFAR 100 where you have 100 different classes of images.

The problem is that we cannot just take a photo and give it to the computer.

We must design a way to turn that photo into numbers in order to communicate the image to the computer.


This is where linear algebra comes in

Each photo has some dimensions.

Say this photo is 400 by 400 

>. Each pixel in a photo is basically a colour square
(zoom in until we see pixels)

>. giving enough pixel and given enough zoom out causes our brain to perceive this as an image rather than a collection of squares.
(zoom out to reach the photo)

In [ ]:
EXAMPLE

We have 256 shades of gray shade.

0 is totally white

255 is totally black or vice versa.

We can actually express this photo as a matrix.

If the photo is 400  x 400 then we have a 400 x 400 matrix..

Each element of that matrix is a number from 255

height = 400

> it shows the intensity of the color grey in that pixel.

That is how the computer sees a photo.



 How to reprsent colour

So far we have two dimensions;
weight and heights

But the number inside corresponds to the intensity of colour.

What if we want more colours ?

We will use the R G B scale to solve it.

R G b stands for red green and blue.

the idea is tha any colour perceiveable

by the human eyes can be decomposed into some combinations of red ,green and blue.

But the intensity of each colour is from 0 - 255

A total of 256 shades

In other to represent a colored photo in some linear algebraic form,

We must take the example from before and add another dimension color

Instead of 400 by 400, we get a three dimension 

3 x 400 x 400 Tensors

This Tensor contains 3 , 400 x 400 matrices

one for each coluor, red ,green and blue 

And that is how deep neuro networks works with photos.

##### Dimensionality Reduction

Since we have not seen
.> Eigenvalues

.> Eigenvectors 

yet .

There is not much to say here ,aside from developing some intuition.

Imagine we have a dataset with 3 variables 

Vitually our data may look like a  scatter plot

To be able to represent each of the point, we have used 3 values.

One for each variable x, y ,z.

(x y, 3)

Hence, we are dealing with m x 3 matrix.

Therefore the point i corresponds to 
xi, yi and zi

Note that those 3 variables  xi, yi,zi are the 3 axis of the plane

In some cases we can find the plane very close to the data.

This plane is 2 dimentional nad is defined by 2 variables.

For example 

u ,v 

Not all points lie on this plane but we can confidently say that they do.

Linear algebra provides us with fast and  efficient ways to transform our matric from m x 3 where the 3 variables are x,y,z into a new matrix which is m x 2 where the two variables are u, v.

In this way, instead of having 3 variables , we reduced the problem to 2 variables

Infact, if you have 50 variables, you can reuce them to 40 or 20 or even 10.

How does this relate to the real world?

Imagine a survey that have a total of 50 questions.

Three of them are the following:

Please rate from 1 to 5

.1 i feel comfortable around people

.2 I easily make friends

.3 I like going out

Thes questions may seem differnt but in the general case they are not.

They all measure your level of extraversion.

So it makes sense to combine them.

This is where 
Dimensional reduction and linear algebra come in.


Very often we have too many variables that are not so different, so we would like to reduce the complexity of the problem by reducing the number of variables.

